#!/usr/bin/env python3
"""Build BMC manuscript/admin files from verified committed sources.

Run this with the Codex bundled document Python runtime, which provides python-docx.
Figures must first be generated by ``scripts/build_bmc_figures.py``.
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
import shutil
import subprocess
import zipfile
from datetime import date
from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / "paper/bmc_bioinformatics"
FINAL = WORK / "final"
FIGURES = FINAL / "figures"
ADDITIONAL = FINAL / "additional_files"
SOURCE = WORK / "MANUSCRIPT_SOURCE.md"
FROZEN_COMMIT = "de7868a83d3d1e30729323e53a735615d43fc231"
ARTICLE_TITLE = (
    "ViralSafeTarget: evidence-aware, virus-first CRISPR target prioritization "
    "with an exhaustive HSV-2 case study"
)


def _font(run, *, size: float = 12, bold: bool = False, italic: bool = False, color=None):
    run.font.name = "Times New Roman"
    run._element.get_or_add_rPr().rFonts.set(qn("w:ascii"), "Times New Roman")
    run._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"), "Times New Roman")
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic
    if color:
        run.font.color.rgb = RGBColor(*color)


def _set_cell_margins(cell, top=90, start=120, bottom=90, end=120):
    tc = cell._tc
    tc_pr = tc.get_or_add_tcPr()
    tc_mar = tc_pr.first_child_found_in("w:tcMar")
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)
    for tag, value in (("top", top), ("start", start), ("bottom", bottom), ("end", end)):
        node = tc_mar.find(qn(f"w:{tag}"))
        if node is None:
            node = OxmlElement(f"w:{tag}")
            tc_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def _set_repeat_header(row):
    tr_pr = row._tr.get_or_add_trPr()
    tbl_header = OxmlElement("w:tblHeader")
    tbl_header.set(qn("w:val"), "true")
    tr_pr.append(tbl_header)


def _set_table_geometry(table, widths):
    total = sum(widths)
    table.autofit = False
    tbl_pr = table._tbl.tblPr
    tbl_w = tbl_pr.first_child_found_in("w:tblW")
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.append(tbl_w)
    tbl_w.set(qn("w:w"), str(total))
    tbl_w.set(qn("w:type"), "dxa")
    tbl_ind = tbl_pr.first_child_found_in("w:tblInd")
    if tbl_ind is None:
        tbl_ind = OxmlElement("w:tblInd")
        tbl_pr.append(tbl_ind)
    tbl_ind.set(qn("w:w"), "120")
    tbl_ind.set(qn("w:type"), "dxa")
    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths:
        col = OxmlElement("w:gridCol")
        col.set(qn("w:w"), str(width))
        grid.append(col)
    for row in table.rows:
        for cell, width in zip(row.cells, widths, strict=True):
            tc_pr = cell._tc.get_or_add_tcPr()
            tc_w = tc_pr.first_child_found_in("w:tcW")
            if tc_w is None:
                tc_w = OxmlElement("w:tcW")
                tc_pr.append(tc_w)
            tc_w.set(qn("w:w"), str(width))
            tc_w.set(qn("w:type"), "dxa")
            _set_cell_margins(cell)
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def _configure_document(doc: Document, *, double_spaced: bool = True, line_numbers=True):
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = section.bottom_margin = Inches(1)
    section.left_margin = section.right_margin = Inches(1)
    section.header_distance = Inches(0.45)
    section.footer_distance = Inches(0.45)

    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal._element.rPr.rFonts.set(qn("w:ascii"), "Times New Roman")
    normal._element.rPr.rFonts.set(qn("w:hAnsi"), "Times New Roman")
    normal.font.size = Pt(12)
    normal.paragraph_format.space_after = Pt(0)
    normal.paragraph_format.line_spacing_rule = (
        WD_LINE_SPACING.DOUBLE if double_spaced else WD_LINE_SPACING.SINGLE
    )
    for name, size, before, after in (
        ("Heading 1", 14, 12, 6),
        ("Heading 2", 12, 10, 4),
        ("Heading 3", 12, 8, 3),
    ):
        style = doc.styles[name]
        style.font.name = "Times New Roman"
        style._element.rPr.rFonts.set(qn("w:ascii"), "Times New Roman")
        style._element.rPr.rFonts.set(qn("w:hAnsi"), "Times New Roman")
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor(0, 0, 0)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)
        style.paragraph_format.keep_with_next = True

    if "Table Title" not in doc.styles:
        style = doc.styles.add_style("Table Title", WD_STYLE_TYPE.PARAGRAPH)
        style.font.name = "Times New Roman"
        style.font.size = Pt(11)
        style.font.bold = True
        style.paragraph_format.space_before = Pt(6)
        style.paragraph_format.space_after = Pt(3)
        style.paragraph_format.keep_with_next = True

    header = section.header.paragraphs[0]
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header.add_run("DO NOT SUBMIT — HUMAN REVIEW AND AUTHOR METADATA PENDING")
    _font(run, size=9, bold=True, color=(180, 35, 24))

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Page ")
    _font(run, size=9)
    fld_char1 = OxmlElement("w:fldChar")
    fld_char1.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = " PAGE "
    fld_char2 = OxmlElement("w:fldChar")
    fld_char2.set(qn("w:fldCharType"), "end")
    run._r.extend([fld_char1, instr, fld_char2])

    if line_numbers:
        sect_pr = section._sectPr
        ln = sect_pr.find(qn("w:lnNumType"))
        if ln is None:
            ln = OxmlElement("w:lnNumType")
            sect_pr.append(ln)
        ln.set(qn("w:countBy"), "1")
        ln.set(qn("w:start"), "1")
        ln.set(qn("w:restart"), "continuous")


def _add_rich_text(paragraph, text: str):
    # Minimal Markdown emphasis parser for source-authored manuscript text.
    pieces = re.split(r"(\*\*.*?\*\*|`.*?`)", text)
    for piece in pieces:
        if not piece:
            continue
        if piece.startswith("**") and piece.endswith("**"):
            run = paragraph.add_run(piece[2:-2])
            _font(run, bold=True)
        elif piece.startswith("`") and piece.endswith("`"):
            run = paragraph.add_run(piece[1:-1])
            run.font.name = "Courier New"
            run.font.size = Pt(10)
        else:
            run = paragraph.add_run(piece)
            _font(run)


def _add_table(doc, title, headers, rows, widths):
    doc.add_paragraph(title, style="Table Title")
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    _set_repeat_header(table.rows[0])
    for cell, value in zip(table.rows[0].cells, headers, strict=True):
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(str(value))
        _font(run, size=9, bold=True)
    for values in rows:
        cells = table.add_row().cells
        for cell, value in zip(cells, values, strict=True):
            p = cell.paragraphs[0]
            if isinstance(value, (int, float)):
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(str(value))
            _font(run, size=9)
    _set_table_geometry(table, widths)
    legend = doc.add_paragraph()
    legend.paragraph_format.space_before = Pt(3)
    legend.paragraph_format.space_after = Pt(6)
    legend.paragraph_format.line_spacing = 1
    run = legend.add_run(
        "Values are computational and model-bounded; missing evidence remains unknown."
    )
    _font(run, size=9, italic=True)


def _publication_tables(doc, trigger):
    stats = json.loads((FINAL / "verified_statistics.json").read_text())
    if trigger == "Exhaustive HSV-2 source validation":
        rows = [
            ("Initial candidate coordinates", f"{stats['initial_candidates']:,}"),
            ("Eligible candidate-coordinate rows", f"{stats['eligible_candidates']:,}"),
            ("Unique guide sequences", f"{stats['unique_guides']:,}"),
            (
                "Cas-OFFinder batches completed",
                f"{stats['completed_batches']}/{stats['total_batches']}",
            ),
            ("Predicted human-match rows", f"{stats['human_matches']:,}"),
            ("Zero-hit candidate rows under model", f"{stats['zero_hit_rows']:,}"),
        ]
        _add_table(
            doc,
            "Table 1. Exhaustive HSV-2 analysis summary",
            ["Metric", "Verified value"],
            rows,
            [6600, 2760],
        )
    elif trigger == "Guide rank and gene targetability diverged":
        genes = pd.read_csv(ROOT / "reports/hsv2_genome_wide_exhaustive/gene_rankings.csv")
        focus = ["UL3", "UL10", "UL52", "UL47", "UL11", "UL30", "UL18", "UL19", "UL36"]
        d = genes[genes.gene_name.isin(focus)].sort_values("targetability_rank")
        rows = [
            (
                r.gene_name,
                int(r.targetability_rank),
                f"{r.targetability_score:.3f}",
                int(r.clean_candidate_count),
                r.best_candidate_id,
            )
            for r in d.itertuples()
        ]
        _add_table(
            doc,
            "Table 2. Selected HSV-2 gene-targetability results",
            ["Gene", "Rank", "Score", "Zero-hit rows", "Best candidate"],
            rows,
            [900, 700, 900, 1250, 5610],
        )
    elif trigger == "The deep panel added coding and sequence-robustness context":
        rows = [
            ("Frozen guides", "257"),
            ("Guide-to-CDS mappings", "271"),
            ("Guides mapped to at least one CDS", "250"),
            ("Bounded indel hypotheses", "5,691"),
            ("Single-nucleotide counterfactuals", "17,733"),
            ("Held-out observations available", "200/257"),
        ]
        _add_table(
            doc, "Table 3. Frozen-panel virtual analysis", ["Metric", "Value"], rows, [6600, 2760]
        )
    elif trigger == "Host-search engines agreed while composite ranks addressed a different axis":
        rows = [
            ("Cas-OFFinder vs CRISPRitz Spearman", "0.880413"),
            ("Top-10 overlap", "9/10"),
            ("Top-25 overlap", "24/25"),
            ("Top-50 overlap", "49/50"),
            ("VST pre-host vs post-host Spearman", "0.961975"),
        ]
        _add_table(
            doc,
            "Table 4. Frozen-panel benchmark summary",
            ["Comparison", "Result"],
            rows,
            [6600, 2760],
        )


def build_manuscript() -> Path:
    source = SOURCE.read_text(encoding="utf-8")
    doc = Document()
    _configure_document(doc, double_spaced=True, line_numbers=True)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(18)
    p.paragraph_format.space_after = Pt(12)
    run = p.add_run(ARTICLE_TITLE)
    _font(run, size=16, bold=True)
    for line, size, bold in (
        ("Software Article — BMC Bioinformatics", 12, True),
        ("DO NOT SUBMIT — HUMAN REVIEW PENDING", 12, True),
        ("Ron Nuriel¹*", 12, False),
        ("¹[AFFILIATION REQUIRED]", 11, False),
        ("*Correspondence: [EMAIL REQUIRED]", 11, False),
    ):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_after = Pt(4)
        color = (180, 35, 24) if "DO NOT SUBMIT" in line else None
        run = p.add_run(line)
        _font(run, size=size, bold=bold, color=color)

    # Skip source title-page metadata; start parsing at Abstract.
    lines = source.splitlines()
    start = next(i for i, line in enumerate(lines) if line == "## Abstract")
    paragraph_buffer: list[str] = []

    def flush():
        if not paragraph_buffer:
            return
        text = " ".join(x.strip() for x in paragraph_buffer).strip()
        paragraph_buffer.clear()
        if text:
            p = doc.add_paragraph()
            p.paragraph_format.widow_control = True
            _add_rich_text(p, text)

    current_h2 = ""
    for line in lines[start:]:
        if not line.strip():
            flush()
            continue
        if line.startswith("## "):
            flush()
            current_h2 = line[3:].strip()
            doc.add_heading(current_h2, level=1)
            continue
        if line.startswith("### "):
            flush()
            heading = line[4:].strip()
            doc.add_heading(heading, level=2)
            if current_h2 == "Results":
                _publication_tables(doc, heading)
            continue
        if line.startswith("- "):
            flush()
            p = doc.add_paragraph(style="List Bullet")
            p.paragraph_format.left_indent = Inches(0.5)
            p.paragraph_format.first_line_indent = Inches(-0.25)
            p.paragraph_format.keep_together = True
            _add_rich_text(p, line[2:])
            continue
        if current_h2 == "References" and re.match(r"^\d+\.\s", line):
            flush()
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.25)
            p.paragraph_format.first_line_indent = Inches(-0.25)
            p.paragraph_format.keep_together = True
            _add_rich_text(p, line)
            continue
        paragraph_buffer.append(line)
    flush()

    output = FINAL / "Main_Manuscript_BMC_Bioinformatics.docx"
    FINAL.mkdir(parents=True, exist_ok=True)
    doc.save(output)
    shutil.copy2(SOURCE, FINAL / "Main_Manuscript_BMC_Bioinformatics.md")
    return output


def _build_simple_doc(path, title, paragraphs, *, letter=False):
    doc = Document()
    _configure_document(doc, double_spaced=not letter, line_numbers=False)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER if not letter else WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(title)
    _font(run, size=15, bold=True)
    for text in paragraphs:
        p = doc.add_paragraph()
        p.paragraph_format.line_spacing = 1.15 if letter else 2
        _add_rich_text(p, text)
    doc.save(path)


def build_admin_files():
    _build_simple_doc(
        FINAL / "Cover_Letter_BMC_Bioinformatics.docx",
        "Cover letter — BMC Bioinformatics",
        [
            "[DATE REQUIRED]",
            "Dear Editors of BMC Bioinformatics,",
            f"Please consider our manuscript, “{ARTICLE_TITLE},” as a Software Article.",
            (
                "The software addresses a broad bioinformatics need: moving from viral genomes "
                "to an auditable research shortlist while keeping viral conservation, "
                "model-bounded host search, guide rank, gene targetability, predicted coding "
                "disruption, evidence provenance and exact-target multiplex robustness explicit. "
                "The manuscript includes an exhaustive HSV-2 case study, a direct frozen-panel "
                "comparison with Cas-OFFinder and CRISPRitz, sensitivity analysis, an "
                "installed-wheel portability test and a second-virus operational check."
            ),
            (
                "The work fits the journal’s scope in sequence analysis, comparative genomics "
                "and reproducible software. The public MIT-licensed repository and source "
                "archive permit anonymous reviewer testing. We do not claim experimental "
                "editing, safety, viral inhibition, delivery, treatment or cure."
            ),
            (
                "The author declares no competing interests. [AUTHOR CONFIRMATION REQUIRED] "
                "All authors have approved the manuscript and its submission. "
                "[AUTHOR CONFIRMATION REQUIRED] The manuscript has not been published or "
                "submitted elsewhere. [AUTHOR CONFIRMATION REQUIRED]"
            ),
            "Sincerely,\nRon Nuriel\n[AFFILIATION REQUIRED]\n[EMAIL REQUIRED]",
        ],
        letter=True,
    )
    _build_simple_doc(
        FINAL / "Title_Page_and_Submission_Metadata.docx",
        "Title page and submission metadata",
        [
            f"Title: {ARTICLE_TITLE}",
            "Article type: Software Article",
            "Author: Ron Nuriel",
            "Affiliation: [AFFILIATION REQUIRED]",
            "Corresponding author email: [EMAIL REQUIRED]",
            "ORCID: [ORCID OPTIONAL/REQUIRED IF AVAILABLE]",
            (
                "Submission status: DO NOT SUBMIT — human evidence review, author metadata, "
                "DOI and declarations remain pending."
            ),
        ],
    )
    metadata = {
        "journal": "BMC Bioinformatics",
        "article_type": "Software Article",
        "title": ARTICLE_TITLE,
        "authors": [{"name": "Ron Nuriel", "affiliation": "[REQUIRED]", "email": "[REQUIRED]"}],
        "software_version": "0.10.0",
        "frozen_source_commit": FROZEN_COMMIT,
        "doi": "[DOI PENDING]",
        "status": "DO NOT SUBMIT",
    }
    (FINAL / "BMC_Submission_Metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")


def build_review_queue():
    evidence = pd.read_csv(ROOT / "reports/hsv2_gene_function/gene_evidence.tsv", sep="\t")
    rows = []
    for i, row in evidence.iterrows():
        source_id = str(row.get("source_identifier", ""))
        issue = (
            "Verify tested virus, experimental design, phenotype and bounded manuscript wording."
        )
        if source_id == "PMID:24794394":
            issue = (
                "CRITICAL: PubMed title identifies HSV-1, while the committed row labels "
                "virus_type HSV-2/strain_333. Resolve before any use."
            )
        rows.append(
            {
                "review_id": f"EVID-{i + 1:03d}",
                "gene": row.get("gene_name", ""),
                "target_virus": "HSV-2",
                "evidence_virus_in_table": row.get("virus_type", ""),
                "source_identifier": source_id,
                "source_url": row.get("source_url", ""),
                "claim_or_finding": row.get("finding", ""),
                "review_issue": issue,
                "status": "pending",
                "reviewer_name": "",
                "review_date": "",
                "source_checked": "",
                "decision": "",
                "approved_or_edited_wording": "",
            }
        )
    pd.DataFrame(rows).to_csv(FINAL / "HUMAN_REVIEW_REQUIRED.csv", index=False)


def build_text_admin():
    checklist = """# BMC pre-submission checklist

**STATUS: DO NOT SUBMIT**

- [x] Software Article section structure matches current BMC guidance.
- [x] Structured abstract is <=350 words.
- [x] DOCX uses double spacing, page numbers and continuous line numbers.
- [x] Tables are editable and unshaded.
- [x] Figures are separate PDF/PNG files and below 10 MB.
- [x] Numerical claims are asserted from committed sources.
- [ ] Affiliation and corresponding-author email supplied.
- [ ] All human-review rows resolved by named domain-qualified reviewer(s).
- [ ] Asterisks removed only for resolved claims.
- [ ] DOI minted and DOI placeholders replaced.
- [ ] Funding, competing interests, contributions and acknowledgements confirmed.
- [ ] All authors approved submission and confirmed no simultaneous submission.
- [ ] Potential reviewers independently chosen and verified by the author, if supplied.
- [ ] Final author read-through and reference-manager audit completed.
"""
    (FINAL / "BMC_PreSubmission_Checklist.md").write_text(checklist)
    upload = """# BMC upload map

| Submission item | File |
|---|---|
| Main manuscript | `Main_Manuscript_BMC_Bioinformatics.docx` |
| Cover letter | `Cover_Letter_BMC_Bioinformatics.docx` |
| Title page metadata | `Title_Page_and_Submission_Metadata.docx` |
| Figures | `figures/Figure_1.pdf` through `Figure_6.pdf` |
| Additional file 1 | `additional_files/Additional_file_1_Supplementary_Figure_S1.pdf` |
| Additional file 2 | `additional_files/Additional_file_2_Machine_Readable_Tables.zip` |
| Additional file 3 | `additional_files/Additional_file_3_ViralSafeTarget_0.10.0_Source.zip` |

Do not upload until the checklist has no unresolved blocking items.
"""
    (FINAL / "BMC_Upload_Map.md").write_text(upload)
    with (FINAL / "Potential_Reviewers_Template.csv").open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "name",
                "institution",
                "institutional_email",
                "ORCID_or_Scopus",
                "expertise",
                "conflict_check",
                "author_verified",
            ]
        )
    zenodo = {
        "title": "ViralSafeTarget 0.10.0: source and HSV-2 computational case-study artifacts",
        "description": (
            "Reproducible virus-first CRISPR target prioritization software and compact "
            "computational result snapshots. No experimental or therapeutic claim."
        ),
        "creators": [{"name": "Nuriel, Ron", "affiliation": "[AFFILIATION REQUIRED]"}],
        "license": "MIT",
        "upload_type": "software",
        "version": "0.10.0",
        "keywords": ["bioinformatics", "viral genomics", "CRISPR", "HSV-2", "reproducibility"],
        "related_identifiers": [
            {
                "identifier": "https://github.com/ronnuriel/ViralSafeTarget",
                "relation": "isSupplementTo",
                "scheme": "url",
            }
        ],
    }
    (ROOT / ".zenodo.json").write_text(json.dumps(zenodo, indent=2) + "\n")


def build_additional_files():
    ADDITIONAL.mkdir(parents=True, exist_ok=True)
    tables = [
        "reports/hsv2_genome_wide_exhaustive/gene_rankings.csv",
        "reports/hsv2_genome_wide_exhaustive/top_candidates_global.csv",
        "reports/hsv2_genome_wide_exhaustive/deep_screening_panel.csv",
        "reports/hsv2_virtual_knockout_escape/gene_virtual_knockout.csv",
        "reports/hsv2_virtual_knockout_escape/strategy_comparison.csv",
        "reports/hsv2_tool_benchmark/rank_agreement.csv",
        "reports/hsv2_tool_benchmark/top_k_overlap.csv",
        "reports/hsv2_tool_benchmark/ablation_summary.csv",
        "reports/hsv2_tool_benchmark/tool_capability_evidence.csv",
    ]
    with zipfile.ZipFile(
        ADDITIONAL / "Additional_file_2_Machine_Readable_Tables.zip", "w", zipfile.ZIP_DEFLATED
    ) as zf:
        for relative in tables:
            zf.write(ROOT / relative, relative)
        zf.write(FINAL / "verified_statistics.json", "verified_statistics.json")
    source_zip = ADDITIONAL / "Additional_file_3_ViralSafeTarget_0.10.0_Source.zip"
    subprocess.run(
        [
            "git",
            "archive",
            "--format=zip",
            "--prefix=ViralSafeTarget-0.10.0/",
            "-o",
            str(source_zip),
            FROZEN_COMMIT,
        ],
        cwd=ROOT,
        check=True,
    )
    digest = hashlib.sha256(source_zip.read_bytes()).hexdigest()
    (ADDITIONAL / "Additional_file_3_SHA256.txt").write_text(f"{digest}  {source_zip.name}\n")


def count_abstract_words() -> int:
    source = SOURCE.read_text()
    abstract = source.split("## Abstract", 1)[1].split("**Keywords:**", 1)[0]
    abstract = re.sub(r"^#+\s*", "", abstract, flags=re.M)
    return len(re.findall(r"\b[\w–-]+\b", abstract))


def main():
    FINAL.mkdir(parents=True, exist_ok=True)
    for figure in [*(FIGURES.glob("Figure_*.pdf")), *(FIGURES.glob("Figure_*.png"))]:
        if figure.stat().st_size >= 10 * 1024 * 1024:
            raise AssertionError(f"Figure exceeds 10 MB: {figure}")
    count = count_abstract_words()
    if count > 350:
        raise AssertionError(f"Abstract is {count} words; BMC limit is 350")
    build_manuscript()
    build_admin_files()
    build_review_queue()
    build_text_admin()
    build_additional_files()
    (FINAL / "build_metadata.json").write_text(
        json.dumps(
            {
                "status": "DO NOT SUBMIT",
                "abstract_word_count": count,
                "frozen_source_commit": FROZEN_COMMIT,
                "build_date": date.today().isoformat(),
                "human_review_resolved": 0,
                "human_review_pending": len(pd.read_csv(FINAL / "HUMAN_REVIEW_REQUIRED.csv")),
            },
            indent=2,
        )
        + "\n"
    )
    print(f"Built BMC working package; abstract words={count}")


if __name__ == "__main__":
    main()
